In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])

In [7]:
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)#1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [14]:
#2d array
arr3=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
